module.exports={
    error:"Hubo un error.",
    errorIdExistente:"Ya existe un registro con ese ID.",
    errorIdEmpleadoExistente:"Ya existe un registro con ese ID de empleado.",
    errorCorreoExistente:"Ya existe un registro con ese correo.",
    errorRolInexistente:"El rol que quería asignar no existe.",
    errorEmpleadosInexistentes:"No hay empleados registrados.",
    errorEmpleadoInexistente:"El empleado no existe.",
    errorNoUsernamePassword:"El nombre de usuario y la contraseña son requeridos.",
    errorWrongUsernamePassword:"Nombre de usuario o contraseña incorrectos.",
    errorPermiso:"No tiene permisos de acceso a la aplicación",
    errorIdObligatorio:"El ID es obligatorio.",
    errorFirstNameObligatorio:"El primer nombre es obligatorio",
    errorFirstLastNameObligatorio:"El primer apellido es obligatorio.",
    errorEmail:"Debe ingresar un correo electrónico válido.",
    errorBirthdayObligatorio:"La fecha de nacimiento es obligatoria.",
    errorPhoneObligatorio:"El número telefónico es obligatorio.",
    errorSalary:"El salario es obligatorio y debe ser un número mayor a 0.",
    errorRolObligatorio:"El rol del empleado es obligatorio.",
    errorUsuarioInexistente:"El nombre de usuario no existe.",
    errorUsuarioExistente:"El nombre de usuario ya existe.",
    errorNombreObligatorio:"El nombre es obligatorio.",
    errorRazaObligatorio:"La raza es obligatoria.",
    errorTamañoObligatorio:"El tamaño es obligatorio",
    errorAñoObligatorio:"El año de nacimiento (aproximado) es obligatorio",
    errorPlanObligatorio:"La ruta del archivo Plan de Vacunación es obligatoria.",
    errorCuidadosObligatorio:"La ruta del archivo Cuidados es obligatoria.",
    errorPropietariosInexistentes:"No hay propietario registrados.",
}