const bcrypt=require('bcrypt');
module.exports=(sequelize,type)=>{
    return sequelize.define('empleado',{
        id:{
            type:type.STRING,
            primaryKey:true,
        },
        firstName:{
            type:type.STRING(150),
            allowNull:false
        },
        secondName:{
            type:type.STRING(150),
            allowNull:true
        },
        firstlastName:{
            type:type.STRING(150),
            allowNull:false
        },
        secondlastName:{
            type:type.STRING(150),
            allowNull:true
        },
        email:{
            type:type.STRING(200),
            unique:true,
            allowNull:false,
            validate:{
                isEmail:{
                    msg:'No es una dirección de correo electronico'
                }
            }
        },       
        birthday:{
            type:type.DATE,
            allowNull:false
        },
        phoneNumber:{
            type:type.STRING,
            allowNull:false
        },
        salary:{
            type:type.INTEGER,
            allowNull:false
        },
        isActive:{
            type:type.INTEGER,
            allowNull:false,
            defaultValue:1
        },
        role:{
            type:type.STRING(200),
            allowNull:false
        }
    })
}