const bcrypt=require('bcrypt');
module.exports=(sequelize,type)=>{
    return sequelize.define('empleado',{
        id:{
            type:type.STRING,
            primaryKey:true,
        },
        firstName:{
            type:type.STRING(150),
            notNull:true
        },
        secondName:{
            type:type.STRING(150),
            notNull:false
        },
        lastName:{
            type:type.STRING(150),
            notNull:true
        },
        email:{
            type:type.STRING(200),
            unique:true,
            notNull:true,
            validate:{
                isEmail:{
                    msg:'No es una dirección de correo electronico'
                }
            }
        },       
        birthday:{
            type:type.DATE,
            notNull:true
        },
        phoneNumber:{
            type:type.STRING,
            notNull:true
        },
        salary:{
            type:type.INTEGER,
            notNull:true
        },
        isActive:{
            type:type.INTEGER,
            notNull:true,
            defaultValue:1
        }
    })
}